name: PR - Testing

on: [pull_request]

jobs:
  cypress-run:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v1
      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Run tests
        uses: cypress-io/github-action@v2.3.4
        with:
          install: false
          browser: chrome
          start: npm run start
          wait-on: "http://localhost:3000"
          config: baseUrl=http://localhost:3000,defaultCommandTimeout=10000
